# PostgreSQL
#   gem install pq
#
#   Ensure the pq 0.18.4 gem is defined in your Gemfile
#   gem 'pq'
#



default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  username: postgres
  password: 12345678

development:
  <<: *default
  database: ShopOnline_development

test:
  <<: *default
  database: ShopOnline_test

production:
  <<: *default
  database: ShopOnline_production
